"""Núcleo da SDK: HTTP, transporte, erros, retry, ambiente e tipos."""

from .env import ENV_VARS, config_from_env
from .errors import (
    ApiBrasilError,
    ApiBrasilPermissionError,
    ApiBrasilTimeoutError,
    AuthenticationError,
    InsufficientBalanceError,
    NetworkError,
    NotFoundError,
    PermissionError,
    RateLimitError,
    ServerError,
    TimeoutError,
    ValidationError,
    create_api_error,
)
from .http import DEFAULT_BASE_URL, DEFAULT_TIMEOUT, SDK_USER_AGENT, HttpClient
from .retry import DEFAULT_RETRY, backoff_delay_ms, resolve_retry
from .transport import (
    RequestsTransport,
    Transport,
    TransportRequest,
    TransportResponse,
    UrllibTransport,
    default_transport,
)
from .types import (
    ApiBrasilConfig,
    ApiBrasilHooks,
    ConsultaPayload,
    CreditServiceResponse,
    DeviceServiceResponse,
    HookRequestInfo,
    HookResponseInfo,
    HookRetryInfo,
    HttpMethod,
    Json,
    RequestOptions,
    ResponseType,
    RetryConfig,
)

__all__ = [
    "HttpClient",
    "DEFAULT_BASE_URL",
    "DEFAULT_TIMEOUT",
    "SDK_USER_AGENT",
    "Transport",
    "TransportRequest",
    "TransportResponse",
    "RequestsTransport",
    "UrllibTransport",
    "default_transport",
    "ApiBrasilError",
    "NetworkError",
    "TimeoutError",
    "ValidationError",
    "AuthenticationError",
    "InsufficientBalanceError",
    "PermissionError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "ApiBrasilPermissionError",
    "ApiBrasilTimeoutError",
    "create_api_error",
    "DEFAULT_RETRY",
    "resolve_retry",
    "backoff_delay_ms",
    "ENV_VARS",
    "config_from_env",
    "ApiBrasilConfig",
    "ApiBrasilHooks",
    "ConsultaPayload",
    "CreditServiceResponse",
    "DeviceServiceResponse",
    "HookRequestInfo",
    "HookResponseInfo",
    "HookRetryInfo",
    "HttpMethod",
    "Json",
    "RequestOptions",
    "ResponseType",
    "RetryConfig",
]
